FROM nginx/nginx-prometheus-exporter:latest
CMD ["-nginx.scrape-uri", "http://192.168.0.53:8080/nginx_status"]
#NOTE CHANGE THE IP ADDRESS WITH YOUR IP ADDRESS##
#Dockerfile created by Andy Martinez @andymartinezot in linkedin
