version: '3.7'

services:

  proxy-service:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
#docker-compose created by Andy Martinez @andymartinezot in linkedin