scrape_configs:
  - job_name: 'nginx-website'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.0.53:9113'] ##NOTE CHANGE THE IP ADDRESS WITH YOUR IP ADDRESS##
#yaml file created by Andy Martinez @andymartinezot in linkedin