FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/nginx.conf
#EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
WORKDIR /usr/share/nginx/html
#Dockerfile created by Andy Martinez @andymartinezot in linkedin